// Generated by scripts/build.js. Do not edit.

export const iconNames = [
	'eye-slash',
	'link',
	'list-bullets',
	'list-numbers',
	'quotes',
	'text-bold',
	'text-italic',
] as const

export type IconName = (typeof iconNames)[number]
