// Generated by scripts/build.js. Do not edit.

export const iconNames = [
	'bookmarks-duotone',
	'bookmarks-solid',
	'chevron-up-down',
	'controller-duotone',
	'controller-solid',
	'eye-slash',
	'heart-solid',
	'link',
	'list-bullets',
	'list-numbers',
	'magnifying-glass',
	'plus',
	'quotes',
	'star-solid',
	'text-bold',
	'text-italic',
	'x',
] as const

export type IconName = (typeof iconNames)[number]
