/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'social.respawn.richtext.facet'

export { $nsid }

/** Annotation of a sub-string within rich text. Modeled on app.bsky.richtext.facet with Respawn-specific formatting features. */
type Main = {
  $type?: 'social.respawn.richtext.facet'
  index: ByteSlice
  features: (
    | l.$Typed<Link>
    | l.$Typed<Bold>
    | l.$Typed<Italic>
    | l.$Typed<Spoiler>
    | l.$Typed<Blockquote>
    | l.$Typed<ListItem>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

/** Annotation of a sub-string within rich text. Modeled on app.bsky.richtext.facet with Respawn-specific formatting features. */
const main = /*#__PURE__*/ l.typedObject<Main>(
  $nsid,
  'main',
  /*#__PURE__*/ l.object({
    index: /*#__PURE__*/ l.ref<ByteSlice>((() => byteSlice) as any),
    features: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<Link>((() => link) as any),
          /*#__PURE__*/ l.typedRef<Bold>((() => bold) as any),
          /*#__PURE__*/ l.typedRef<Italic>((() => italic) as any),
          /*#__PURE__*/ l.typedRef<Spoiler>((() => spoiler) as any),
          /*#__PURE__*/ l.typedRef<Blockquote>((() => blockquote) as any),
          /*#__PURE__*/ l.typedRef<ListItem>((() => listItem) as any),
        ],
        false,
      ),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. */
type ByteSlice = {
  $type?: 'social.respawn.richtext.facet#byteSlice'
  byteStart: number
  byteEnd: number
}

export type { ByteSlice }

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. */
const byteSlice = /*#__PURE__*/ l.typedObject<ByteSlice>(
  $nsid,
  'byteSlice',
  /*#__PURE__*/ l.object({
    byteStart: /*#__PURE__*/ l.integer({ minimum: 0 }),
    byteEnd: /*#__PURE__*/ l.integer({ minimum: 0 }),
  }),
)

export { byteSlice }

/** Facet feature for a URL. */
type Link = { $type?: 'social.respawn.richtext.facet#link'; uri: l.UriString }

export type { Link }

/** Facet feature for a URL. */
const link = /*#__PURE__*/ l.typedObject<Link>(
  $nsid,
  'link',
  /*#__PURE__*/ l.object({ uri: /*#__PURE__*/ l.string({ format: 'uri' }) }),
)

export { link }

/** Facet feature for bold text. */
type Bold = { $type?: 'social.respawn.richtext.facet#bold' }

export type { Bold }

/** Facet feature for bold text. */
const bold = /*#__PURE__*/ l.typedObject<Bold>(
  $nsid,
  'bold',
  /*#__PURE__*/ l.object({}),
)

export { bold }

/** Facet feature for italic text. */
type Italic = { $type?: 'social.respawn.richtext.facet#italic' }

export type { Italic }

/** Facet feature for italic text. */
const italic = /*#__PURE__*/ l.typedObject<Italic>(
  $nsid,
  'italic',
  /*#__PURE__*/ l.object({}),
)

export { italic }

/** Facet feature marking a span as a spoiler. In display text the span is scrambled; the original text lives in the accompanying textWithSpoilers field. */
type Spoiler = { $type?: 'social.respawn.richtext.facet#spoiler' }

export type { Spoiler }

/** Facet feature marking a span as a spoiler. In display text the span is scrambled; the original text lives in the accompanying textWithSpoilers field. */
const spoiler = /*#__PURE__*/ l.typedObject<Spoiler>(
  $nsid,
  'spoiler',
  /*#__PURE__*/ l.object({}),
)

export { spoiler }

/** Facet feature for a blockquote span. */
type Blockquote = { $type?: 'social.respawn.richtext.facet#blockquote' }

export type { Blockquote }

/** Facet feature for a blockquote span. */
const blockquote = /*#__PURE__*/ l.typedObject<Blockquote>(
  $nsid,
  'blockquote',
  /*#__PURE__*/ l.object({}),
)

export { blockquote }

/** Facet feature for a list item span. */
type ListItem = {
  $type?: 'social.respawn.richtext.facet#listItem'

  /**
   * Whether the item belongs to an ordered (numbered) list.
   */
  ordered?: boolean
}

export type { ListItem }

/** Facet feature for a list item span. */
const listItem = /*#__PURE__*/ l.typedObject<ListItem>(
  $nsid,
  'listItem',
  /*#__PURE__*/ l.object({
    ordered: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
  }),
)

export { listItem }
