/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextFacet from '../richtext/facet.defs.ts'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.ts'

const $nsid = 'social.respawn.feed.comment'

export { $nsid }

/** A comment on a log or list. Stored in the commenter's repo; the subject's author can hide it via their social.respawn.feed.gate record. */
type Main = {
  $type: 'social.respawn.feed.comment'
  text: string
  facets?: RichtextFacet.Main[]

  /**
   * The root log or list being commented on.
   */
  subject: RepoStrongRef.Main

  /**
   * Optional parent comment, for threaded replies.
   */
  parent?: RepoStrongRef.Main
  createdAt: l.DatetimeString
}

export type { Main }

/** A comment on a log or list. Stored in the commenter's repo; the subject's author can hide it via their social.respawn.feed.gate record. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    text: /*#__PURE__*/ l.string({ maxGraphemes: 3000, maxLength: 30000 }),
    facets: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<RichtextFacet.Main>(
          (() => RichtextFacet.main) as any,
        ),
      ),
    ),
    subject: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    parent: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
