/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'social.respawn.feed.gate'

export { $nsid }

/** Interaction settings for a log or list, analogous to app.bsky.feed.threadgate/postgate. The record key (rkey) must match the rkey of the gated record. Absence of a gate record means everyone can interact. */
type Main = {
  $type: 'social.respawn.feed.gate'

  /**
   * The log or list this gate applies to.
   */
  subject: l.AtUriString

  /**
   * Rules for who can comment. Absent means everyone; an empty array or a nobody rule means no one.
   */
  allow?: (
    | l.$Typed<NobodyRule>
    | l.$Typed<FollowingRule>
    | l.$Typed<FollowerRule>
    | l.Unknown$TypedObject
  )[]
  disableLikes?: boolean

  /**
   * AT-URIs of comments the author has hidden.
   */
  hiddenComments?: l.AtUriString[]
  createdAt: l.DatetimeString
}

export type { Main }

/** Interaction settings for a log or list, analogous to app.bsky.feed.threadgate/postgate. The record key (rkey) must match the rkey of the gated record. Absence of a gate record means everyone can interact. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    subject: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    allow: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.typedUnion(
          [
            /*#__PURE__*/ l.typedRef<NobodyRule>((() => nobodyRule) as any),
            /*#__PURE__*/ l.typedRef<FollowingRule>(
              (() => followingRule) as any,
            ),
            /*#__PURE__*/ l.typedRef<FollowerRule>((() => followerRule) as any),
          ],
          false,
        ),
        { maxLength: 5 },
      ),
    ),
    disableLikes: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    hiddenComments: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'at-uri' }), {
        maxLength: 50,
      }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Disallow comments from everyone. */
type NobodyRule = { $type?: 'social.respawn.feed.gate#nobodyRule' }

export type { NobodyRule }

/** Disallow comments from everyone. */
const nobodyRule = /*#__PURE__*/ l.typedObject<NobodyRule>(
  $nsid,
  'nobodyRule',
  /*#__PURE__*/ l.object({}),
)

export { nobodyRule }

/** Allow comments from actors the author follows. */
type FollowingRule = { $type?: 'social.respawn.feed.gate#followingRule' }

export type { FollowingRule }

/** Allow comments from actors the author follows. */
const followingRule = /*#__PURE__*/ l.typedObject<FollowingRule>(
  $nsid,
  'followingRule',
  /*#__PURE__*/ l.object({}),
)

export { followingRule }

/** Allow comments from actors who follow the author. */
type FollowerRule = { $type?: 'social.respawn.feed.gate#followerRule' }

export type { FollowerRule }

/** Allow comments from actors who follow the author. */
const followerRule = /*#__PURE__*/ l.typedObject<FollowerRule>(
  $nsid,
  'followerRule',
  /*#__PURE__*/ l.object({}),
)

export { followerRule }
