/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RespawnDefs from '../defs.defs.ts'

const $nsid = 'social.respawn.feed.getActivity'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  actor: /*#__PURE__*/ l.string({ format: 'did' }),
  filter: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.string<{
        knownValues: ['all', 'author', 'incoming', 'following']
      }>(),
      'all',
    ),
  ),
  limit: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 50 }),
      30,
    ),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  feed: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<FeedItem>((() => feedItem) as any),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Activity events involving an actor, newest first. `filter` selects the slice. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid

/** One activity event. `type` selects which optional fields are present. */
type FeedItem = {
  $type?: 'social.respawn.feed.getActivity#feedItem'
  type: 'backlogAdd' | 'follow' | 'log' | 'logLike' | l.UnknownString
  uri: l.AtUriString

  /**
   * The actor who performed the action.
   */
  did: l.DidString
  createdAt: l.DatetimeString

  /**
   * Present on backlogAdd, log, and logLike (the liked log's game).
   */
  game?: RespawnDefs.GameRef

  /**
   * Present on backlogAdd.
   */
  cover?: RespawnDefs.Cover

  /**
   * Present on follow: the account followed.
   */
  subject?: l.DidString

  /**
   * Present on log (the log itself) and logLike (the liked log).
   */
  log?: LogView
}

export type { FeedItem }

/** One activity event. `type` selects which optional fields are present. */
const feedItem = /*#__PURE__*/ l.typedObject<FeedItem>(
  $nsid,
  'feedItem',
  /*#__PURE__*/ l.object({
    type: /*#__PURE__*/ l.string<{
      knownValues: ['backlogAdd', 'follow', 'log', 'logLike']
    }>(),
    uri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    did: /*#__PURE__*/ l.string({ format: 'did' }),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    game: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.GameRef>(
        (() => RespawnDefs.gameRef) as any,
      ),
    ),
    cover: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.Cover>((() => RespawnDefs.cover) as any),
    ),
    subject: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'did' }),
    ),
    log: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<LogView>((() => logView) as any),
    ),
  }),
)

export { feedItem }

/** A log as the feed shows it. */
type LogView = {
  $type?: 'social.respawn.feed.getActivity#logView'
  uri: l.AtUriString

  /**
   * The log's author.
   */
  did: l.DidString

  /**
   * 1-based position among the author's logs of this game, oldest first by createdAt. Addresses the log's page.
   */
  number: number

  /**
   * The social.respawn.feed.log record.
   */
  record: l.LexMap
}

export type { LogView }

/** A log as the feed shows it. */
const logView = /*#__PURE__*/ l.typedObject<LogView>(
  $nsid,
  'logView',
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    did: /*#__PURE__*/ l.string({ format: 'did' }),
    number: /*#__PURE__*/ l.integer({ minimum: 1 }),
    record: /*#__PURE__*/ l.lexMap(),
  }),
)

export { logView }
