/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RespawnDefs from '../defs.defs.ts'

const $nsid = 'social.respawn.feed.getTimeline'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  viewer: /*#__PURE__*/ l.string({ format: 'did' }),
  limit: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 50 }),
      30,
    ),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  feed: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<FeedItem>((() => feedItem) as any),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Activity from the accounts a viewer follows, newest first. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid

/** One activity event. `type` selects which optional fields are present. */
type FeedItem = {
  $type?: 'social.respawn.feed.getTimeline#feedItem'
  type: 'backlogAdd' | 'follow' | l.UnknownString
  uri: l.AtUriString

  /**
   * The actor who performed the action.
   */
  did: l.DidString
  createdAt: l.DatetimeString

  /**
   * Present on backlogAdd.
   */
  game?: RespawnDefs.GameRef

  /**
   * Present on backlogAdd.
   */
  cover?: RespawnDefs.Cover

  /**
   * Present on follow: the account followed.
   */
  subject?: l.DidString
}

export type { FeedItem }

/** One activity event. `type` selects which optional fields are present. */
const feedItem = /*#__PURE__*/ l.typedObject<FeedItem>(
  $nsid,
  'feedItem',
  /*#__PURE__*/ l.object({
    type: /*#__PURE__*/ l.string<{ knownValues: ['backlogAdd', 'follow'] }>(),
    uri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    did: /*#__PURE__*/ l.string({ format: 'did' }),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    game: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.GameRef>(
        (() => RespawnDefs.gameRef) as any,
      ),
    ),
    cover: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.Cover>((() => RespawnDefs.cover) as any),
    ),
    subject: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'did' }),
    ),
  }),
)

export { feedItem }
