/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RespawnDefs from '../defs.defs.ts'
import * as RichtextFacet from '../richtext/facet.defs.ts'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.ts'

const $nsid = 'social.respawn.feed.log'

export { $nsid }

/** Record of a play session for a game, optionally including a review. Interaction settings are controlled by a social.respawn.feed.gate record with the same rkey. */
type Main = {
  $type: 'social.respawn.feed.log'
  game: RespawnDefs.GameRef

  /**
   * Edition of the game this session was played on.
   */
  edition?: string

  /**
   * Expansions or DLC included in this session.
   */
  dlc?: string[]
  platform?: string
  cover?: RespawnDefs.Cover
  datePlayed?: l.DatetimeString
  startedPlaying?: boolean
  finishedPlaying?: RespawnDefs.PlayState

  /**
   * Actor's rating, 1-10.
   */
  rating?: number
  liked?: boolean
  review?: Review
  createdAt: l.DatetimeString
}

export type { Main }

/** Record of a play session for a game, optionally including a review. Interaction settings are controlled by a social.respawn.feed.gate record with the same rkey. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    game: /*#__PURE__*/ l.ref<RespawnDefs.GameRef>(
      (() => RespawnDefs.gameRef) as any,
    ),
    edition: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 100, maxLength: 1000 }),
    ),
    dlc: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.string({ maxGraphemes: 100, maxLength: 1000 }),
        { maxLength: 20 },
      ),
    ),
    platform: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 100, maxLength: 1000 }),
    ),
    cover: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.Cover>((() => RespawnDefs.cover) as any),
    ),
    datePlayed: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    startedPlaying: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    finishedPlaying: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.PlayState>(
        (() => RespawnDefs.playState) as any,
      ),
    ),
    rating: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 10 }),
    ),
    liked: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    review: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Review>((() => review) as any),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A review attached to a log. */
type Review = {
  $type?: 'social.respawn.feed.log#review'

  /**
   * Display text. Spans marked with a spoiler facet are scrambled here; naive clients can render this field safely.
   */
  text: string

  /**
   * Original text with spoiler spans unscrambled. Only present when the review contains spoiler facets.
   */
  textWithSpoilers?: string

  /**
   * Whole-review spoiler flag. Clients hide the review text until revealed, unless the viewer has the game in their collection with a completed play state.
   */
  containsSpoilers?: boolean
  facets?: RichtextFacet.Main[]
  external?: External

  /**
   * References to Grain gallery records to display with the review.
   */
  media?: RepoStrongRef.Main[]
}

export type { Review }

/** A review attached to a log. */
const review = /*#__PURE__*/ l.typedObject<Review>(
  $nsid,
  'review',
  /*#__PURE__*/ l.object({
    text: /*#__PURE__*/ l.string({ maxGraphemes: 10000, maxLength: 100000 }),
    textWithSpoilers: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 10000, maxLength: 100000 }),
    ),
    containsSpoilers: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    facets: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<RichtextFacet.Main>(
          (() => RichtextFacet.main) as any,
        ),
      ),
    ),
    external: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<External>((() => external) as any),
    ),
    media: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
          (() => RepoStrongRef.main) as any,
        ),
        { maxLength: 10 },
      ),
    ),
  }),
)

export { review }

/** Reference to an external document (e.g. standard.site) holding the full review. */
type External = {
  $type?: 'social.respawn.feed.log#external'
  uri: l.UriString
  cid?: l.CidString
}

export type { External }

/** Reference to an external document (e.g. standard.site) holding the full review. */
const external = /*#__PURE__*/ l.typedObject<External>(
  $nsid,
  'external',
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.string({ format: 'uri' }),
    cid: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'cid' })),
  }),
)

export { external }
