/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'social.respawn.feed.replygate'

export { $nsid }

/** Who can comment on a log or list, analogous to app.bsky.feed.threadgate. The record key (rkey) must match the rkey of the gated record. Absence of a replygate record means anyone can comment. */
type Main = {
  $type: 'social.respawn.feed.replygate'

  /**
   * The log or list this replygate applies to.
   */
  subject: l.AtUriString

  /**
   * Rules for who can comment, combined as a union. Absent means anyone; an empty array means no one.
   */
  allow?: (
    | l.$Typed<MentionRule>
    | l.$Typed<FollowerRule>
    | l.$Typed<FollowingRule>
    | l.Unknown$TypedObject
  )[]

  /**
   * AT-URIs of comments the author has hidden.
   */
  hiddenComments?: l.AtUriString[]
  createdAt: l.DatetimeString
}

export type { Main }

/** Who can comment on a log or list, analogous to app.bsky.feed.threadgate. The record key (rkey) must match the rkey of the gated record. Absence of a replygate record means anyone can comment. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    subject: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    allow: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.typedUnion(
          [
            /*#__PURE__*/ l.typedRef<MentionRule>((() => mentionRule) as any),
            /*#__PURE__*/ l.typedRef<FollowerRule>((() => followerRule) as any),
            /*#__PURE__*/ l.typedRef<FollowingRule>(
              (() => followingRule) as any,
            ),
          ],
          false,
        ),
        { maxLength: 5 },
      ),
    ),
    hiddenComments: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'at-uri' }), {
        maxLength: 50,
      }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Allow comments from actors mentioned in the gated record's text. */
type MentionRule = { $type?: 'social.respawn.feed.replygate#mentionRule' }

export type { MentionRule }

/** Allow comments from actors mentioned in the gated record's text. */
const mentionRule = /*#__PURE__*/ l.typedObject<MentionRule>(
  $nsid,
  'mentionRule',
  /*#__PURE__*/ l.object({}),
)

export { mentionRule }

/** Allow comments from actors who follow the author. */
type FollowerRule = { $type?: 'social.respawn.feed.replygate#followerRule' }

export type { FollowerRule }

/** Allow comments from actors who follow the author. */
const followerRule = /*#__PURE__*/ l.typedObject<FollowerRule>(
  $nsid,
  'followerRule',
  /*#__PURE__*/ l.object({}),
)

export { followerRule }

/** Allow comments from actors the author follows. */
type FollowingRule = { $type?: 'social.respawn.feed.replygate#followingRule' }

export type { FollowingRule }

/** Allow comments from actors the author follows. */
const followingRule = /*#__PURE__*/ l.typedObject<FollowingRule>(
  $nsid,
  'followingRule',
  /*#__PURE__*/ l.object({}),
)

export { followingRule }
