// Optimizes every icons/icon-*.svg with SVGO and combines them into a single
// <symbol> sprite (src/sprite.svg), plus a typed list of names (src/icon-names.ts).
// The symbol id is the filename minus the `icon-` prefix: icon-text-bold.svg → text-bold.

import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { optimize } from 'svgo'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const iconsDir = path.join(root, 'icons')
const spritePath = path.join(root, 'src/sprite.svg')
const namesPath = path.join(root, 'src/icon-names.ts')

const PREFIX = 'icon-'
// Black is the "draw here" color in source files; it becomes currentColor so
// icons pick up the surrounding text color.
const BLACK = new Set(['#000', '#000000', 'black'])
const ALLOWED_COLORS = new Set(['currentColor', 'none'])
// Root <svg> attributes that don't belong on the <symbol>.
const DROPPED_ROOT_ATTRS = new Set(['xmlns', 'xmlns:xlink', 'width', 'height', 'viewBox'])

/**
 * Rewrites black fill/stroke to currentColor and rejects any other color, so
 * every icon can be recolored with CSS.
 * @param {string} name
 * @returns {import('svgo').CustomPlugin}
 */
function normalizeColors(name) {
	return {
		name: 'normalizeColors',
		fn: () => ({
			element: {
				enter(node) {
					for (const attr of ['fill', 'stroke']) {
						const color = node.attributes[attr]
						if (color === undefined) continue
						if (BLACK.has(color.toLowerCase())) {
							node.attributes[attr] = 'currentColor'
						} else if (!ALLOWED_COLORS.has(color)) {
							throw new Error(
								`${name}: invalid ${attr} "${color}" on <${node.name}>; use black, currentColor or none`,
							)
						}
					}
				},
			},
		}),
	}
}

/**
 * @param {string} name
 * @param {string} raw
 */
function toSymbol(name, raw) {
	const { data } = optimize(raw, {
		multipass: true,
		plugins: [
			// Before preset-default so inline `style="fill:…"` is minified and
			// color-checked like any other attribute.
			'convertStyleToAttrs',
			'preset-default',
			'removeDimensions',
			'removeXMLNS',
			// Keep gradient/clipPath ids unique once icons share a document.
			{ name: 'prefixIds', params: { prefix: name } },
			normalizeColors(name),
			'sortAttrs',
		],
	})

	const match = /^<svg([^>]*)>([\s\S]*)<\/svg>$/.exec(data.trim())
	if (!match) throw new Error(`${name}: unexpected SVGO output: ${data}`)
	const [, rootAttrs, body] = match

	const attrs = Object.fromEntries(
		Array.from(rootAttrs.matchAll(/([\w:-]+)="([^"]*)"/g), ([, key, value]) => [key, value]),
	)
	if (!attrs.viewBox) throw new Error(`${name}: missing viewBox`)

	const symbolAttrs = Object.entries(attrs)
		.filter(([key]) => !DROPPED_ROOT_ATTRS.has(key))
		.map(([key, value]) => ` ${key}="${value}"`)
		.join('')

	return `<symbol id="${name}" viewBox="${attrs.viewBox}"${symbolAttrs}>${body}</symbol>`
}

const files = (await fs.readdir(iconsDir)).filter((file) => file.endsWith('.svg')).toSorted()

const icons = await Promise.all(
	files.map(async (file) => {
		if (!file.startsWith(PREFIX)) {
			throw new Error(`${file}: icon filenames must start with "${PREFIX}"`)
		}
		const name = path.basename(file, '.svg').slice(PREFIX.length)
		const raw = await fs.readFile(path.join(iconsDir, file), 'utf8')
		return { name, symbol: toSymbol(name, raw) }
	}),
)

const sprite = [
	'<svg xmlns="http://www.w3.org/2000/svg">',
	...icons.map(({ symbol }) => symbol),
	'</svg>',
	'',
].join('\n')

const names = [
	'// Generated by scripts/build.js. Do not edit.',
	'',
	'export const iconNames = [',
	...icons.map(({ name }) => `\t'${name}',`),
	'] as const',
	'',
	'export type IconName = (typeof iconNames)[number]',
	'',
].join('\n')

await fs.writeFile(spritePath, sprite)
await fs.writeFile(namesPath, names)

console.log(`Built ${icons.length} icon(s) → ${path.relative(process.cwd(), spritePath)}`)
