/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RespawnDefs from '../defs.defs.ts'

const $nsid = 'social.respawn.actor.backlog'

export { $nsid }

/** The actor's backlog of games to play. A single record per repo. */
type Main = {
  $type: 'social.respawn.actor.backlog'
  games: BacklogItem[]
  createdAt: l.DatetimeString
}

export type { Main }

/** The actor's backlog of games to play. A single record per repo. */
const main = /*#__PURE__*/ l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  /*#__PURE__*/ l.object({
    games: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<BacklogItem>((() => backlogItem) as any),
      { maxLength: 1000 },
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type BacklogItem = {
  $type?: 'social.respawn.actor.backlog#backlogItem'
  game: RespawnDefs.GameRef
  cover?: RespawnDefs.Cover
  releaseDate?: l.DatetimeString
  dateAdded: l.DatetimeString
}

export type { BacklogItem }

const backlogItem = /*#__PURE__*/ l.typedObject<BacklogItem>(
  $nsid,
  'backlogItem',
  /*#__PURE__*/ l.object({
    game: /*#__PURE__*/ l.ref<RespawnDefs.GameRef>(
      (() => RespawnDefs.gameRef) as any,
    ),
    cover: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.Cover>((() => RespawnDefs.cover) as any),
    ),
    releaseDate: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    dateAdded: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { backlogItem }
