/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RespawnDefs from '../defs.defs.ts'

const $nsid = 'social.respawn.actor.profile'

export { $nsid }

/** A Respawn-app profile for an actor. Mirrors app.bsky.actor.profile so existing Bluesky details can prefill it. */
type Main = {
  $type: 'social.respawn.actor.profile'
  displayName?: string

  /**
   * Free-form profile description text.
   */
  description?: string

  /**
   * Small image to be displayed next to the actor's display name.
   */
  avatar?: l.BlobRef
  pronouns?: string

  /**
   * The actor's favorite games.
   */
  faves?: Fave[]

  /**
   * URL of the actor's streaming or video channel.
   */
  channel?: l.UriString

  /**
   * DID of the actor's Bluesky account, so a viewer can open it in their preferred Bluesky client.
   */
  bsky?: l.DidString

  /**
   * How to display adult content to visitors of this profile. Clients default to blur when absent.
   */
  adultContent?: 'show' | 'blur' | 'hide' | l.UnknownString
  createdAt?: l.DatetimeString
}

export type { Main }

/** A Respawn-app profile for an actor. Mirrors app.bsky.actor.profile so existing Bluesky details can prefill it. */
const main = /*#__PURE__*/ l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  /*#__PURE__*/ l.object({
    displayName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 64, maxLength: 640 }),
    ),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 256, maxLength: 2560 }),
    ),
    avatar: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.blob({
        accept: ['image/png', 'image/jpeg', 'image/webp'],
        maxSize: 1000000,
      }),
    ),
    pronouns: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 32, maxLength: 320 }),
    ),
    faves: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.ref<Fave>((() => fave) as any), {
        maxLength: 4,
      }),
    ),
    channel: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    bsky: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'did' })),
    adultContent: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{ knownValues: ['show', 'blur', 'hide'] }>(),
    ),
    createdAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Fave = {
  $type?: 'social.respawn.actor.profile#fave'
  game: RespawnDefs.GameRef
  cover?: RespawnDefs.Cover
}

export type { Fave }

const fave = /*#__PURE__*/ l.typedObject<Fave>(
  $nsid,
  'fave',
  /*#__PURE__*/ l.object({
    game: /*#__PURE__*/ l.ref<RespawnDefs.GameRef>(
      (() => RespawnDefs.gameRef) as any,
    ),
    cover: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.Cover>((() => RespawnDefs.cover) as any),
    ),
  }),
)

export { fave }
