/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'social.respawn.defs'

export { $nsid }

/** A game cover image with optional extracted colors. */
type Cover = {
  $type?: 'social.respawn.defs#cover'
  image: l.BlobRef
  colors?: Colors
}

export type { Cover }

/** A game cover image with optional extracted colors. */
const cover = /*#__PURE__*/ l.typedObject<Cover>(
  $nsid,
  'cover',
  /*#__PURE__*/ l.object({
    image: /*#__PURE__*/ l.blob({
      accept: ['image/png', 'image/jpeg', 'image/webp'],
      maxSize: 1000000,
    }),
    colors: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Colors>((() => colors) as any),
    ),
  }),
)

export { cover }

type Colors = {
  $type?: 'social.respawn.defs#colors'

  /**
   * Dominant cover color as a hex string, e.g. #1a2b3c.
   */
  dominant?: string
}

export type { Colors }

const colors = /*#__PURE__*/ l.typedObject<Colors>(
  $nsid,
  'colors',
  /*#__PURE__*/ l.object({
    dominant: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
)

export { colors }

/** Denormalized reference to a game title, keyed by its IGDB id, so records are self-describing without an IGDB lookup. */
type GameRef = {
  $type?: 'social.respawn.defs#gameRef'
  igdbId: number
  slug: string
  title: string
}

export type { GameRef }

/** Denormalized reference to a game title, keyed by its IGDB id, so records are self-describing without an IGDB lookup. */
const gameRef = /*#__PURE__*/ l.typedObject<GameRef>(
  $nsid,
  'gameRef',
  /*#__PURE__*/ l.object({
    igdbId: /*#__PURE__*/ l.integer({ minimum: 1 }),
    slug: /*#__PURE__*/ l.string({ maxLength: 200 }),
    title: /*#__PURE__*/ l.string({ maxGraphemes: 200, maxLength: 2000 }),
  }),
)

export { gameRef }

/** Play state. Absent means not played. */
type PlayState =
  | 'played'
  | 'completed'
  | 'abandoned'
  | 'retired'
  | 'shelved'
  | l.UnknownString

export type { PlayState }

/** Play state. Absent means not played. */
const playState = /*#__PURE__*/ l.string<{
  knownValues: ['played', 'completed', 'abandoned', 'retired', 'shelved']
}>()

export { playState }
