/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RespawnDefs from './defs.defs.ts'

const $nsid = 'social.respawn.game'

export { $nsid }

/** A game in the actor's collection, keyed by its IGDB id. Stores the current rating, like/play state, and the cover image. Logs are separate social.respawn.feed.log records; creating a log updates this record's current state. */
type Main = {
  $type: 'social.respawn.game'

  /**
   * Actor's rating, 1-10.
   */
  rating?: number
  liked?: boolean
  playing?: boolean
  played?: RespawnDefs.PlayState
  cover?: RespawnDefs.Cover
  createdAt: l.DatetimeString
}

export type { Main }

/** A game in the actor's collection, keyed by its IGDB id. Stores the current rating, like/play state, and the cover image. Logs are separate social.respawn.feed.log records; creating a log updates this record's current state. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    rating: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 10 }),
    ),
    liked: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    playing: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    played: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.PlayState>(
        (() => RespawnDefs.playState) as any,
      ),
    ),
    cover: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.Cover>((() => RespawnDefs.cover) as any),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
