/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextFacet from './richtext/facet.defs.ts'
import * as RespawnDefs from './defs.defs.ts'

const $nsid = 'social.respawn.list'

export { $nsid }

/** A curated list of games. Interaction settings are controlled by a social.respawn.feed.gate record with the same rkey. */
type Main = {
  $type: 'social.respawn.list'
  name: string

  /**
   * URL slug, unique within the actor's repo. Generated from the name.
   */
  slug: string
  description?: Description

  /**
   * Whether item order represents a ranking.
   */
  ranked?: boolean
  items?: Item[]
  createdAt: l.DatetimeString
}

export type { Main }

/** A curated list of games. Interaction settings are controlled by a social.respawn.feed.gate record with the same rkey. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string({ maxGraphemes: 100, maxLength: 1000 }),
    slug: /*#__PURE__*/ l.string({ maxLength: 200 }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Description>((() => description) as any),
    ),
    ranked: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    items: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.ref<Item>((() => item) as any), {
        maxLength: 1000,
      }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Description = {
  $type?: 'social.respawn.list#description'
  text: string
  facets?: RichtextFacet.Main[]
}

export type { Description }

const description = /*#__PURE__*/ l.typedObject<Description>(
  $nsid,
  'description',
  /*#__PURE__*/ l.object({
    text: /*#__PURE__*/ l.string({ maxGraphemes: 3000, maxLength: 30000 }),
    facets: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<RichtextFacet.Main>(
          (() => RichtextFacet.main) as any,
        ),
      ),
    ),
  }),
)

export { description }

type Item = {
  $type?: 'social.respawn.list#item'
  game: RespawnDefs.GameRef
  cover?: RespawnDefs.Cover
}

export type { Item }

const item = /*#__PURE__*/ l.typedObject<Item>(
  $nsid,
  'item',
  /*#__PURE__*/ l.object({
    game: /*#__PURE__*/ l.ref<RespawnDefs.GameRef>(
      (() => RespawnDefs.gameRef) as any,
    ),
    cover: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RespawnDefs.Cover>((() => RespawnDefs.cover) as any),
    ),
  }),
)

export { item }
